tap "caskroom/fonts"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/core"
tap "homebrew/services"
tap "jesseduffield/lazydocker"
tap "universal-ctags/universal-ctags"
brew "ack"
brew "openssl@1.1"
brew "ansible"
brew "asciinema"
brew "awscli"
brew "bat"
brew "black"
brew "cmake"
brew "cmatrix"
brew "cntlm", restart_service: true
brew "colordiff"
brew "ctags", link: false
brew "exa"
brew "fd"
brew "icu4c"
brew "webp"
brew "ffmpeg"
brew "fzf"
brew "git-delta"
brew "glances"
brew "gradle"
brew "graphviz"
brew "htop"
brew "hyperfine"
brew "ipython"
brew "libmagic"
brew "liquidprompt"
brew "macvim"
brew "memcached", restart_service: true
brew "ncdu"
brew "neovim"
brew "nmap"
brew "node"
brew "openconnect"
brew "postgresql"
brew "postgresql@11"
brew "pyenv"
brew "ripgrep"
brew "sl"
brew "telnet"
brew "tig"
brew "tmux"
brew "tree"
brew "unrar"
brew "vim", link: false
brew "watch"
brew "watchman"
brew "wget"
brew "wireshark", link: false
brew "yarn"
brew "ydiff"
brew "youtube-dl", link: false
brew "zlib"
brew "zsh-syntax-highlighting"
brew "jesseduffield/lazydocker/lazydocker"
brew "universal-ctags/universal-ctags/universal-ctags", args: ["HEAD"]
cask "alacritty"
cask "cakebrew"
cask "font-hack-nerd-font"
cask "insomnia"
cask "powershell"
cask "wireshark"
